[project]
name = "streamlit-infrahub"
version = "0.1.0"
description = "Streamlit connection and utilities for Infrahub"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "infrahub-sdk>=1.11.0",
    "polars[pandas]>=1.27.1",
    "streamlit>=1.44.1",
]

[dependency-groups]
dev = [
    "invoke>=2.2.0",
    "mypy>=1.15.0",
    "pytest>=8.3.5",
    "ruff>=0.11.8",
    "yamllint>=1.37.0",
    "pytest-cov>=4.1.0",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
filterwarnings = []
addopts = "-vs --cov=streamlit_infrahub --cov-report=term-missing"

[tool.mypy]
pretty = true
ignore_missing_imports = true
disallow_untyped_defs = true

[tool.ruff]
line-length = 120

exclude = [
    ".git",
    ".venv",
    "env",
    "_build",
    "build",
    "dist",
    "examples",
]


[tool.ruff.lint]
preview = true

task-tags = ["FIXME", "TODO"]

select = ["ALL"]

ignore = [
    "D",      # pydocstyle
    "DOC",    # pydoclint
    "CPY",    # flake8-copyright
    "T201",   # use of `print`
    "ISC",    # flake8-implicit-str-concat
    "COM812", # missing-trailing-comma
    "N999",   # Invalid module name
    "PD901",  # Avoid using the generic variable name `df` for DataFrames
    "TD",
    "FIX",    # TODO
    "TRY",
    "B008",   # Do not perform function call `Depends` in argument defaults
    "EM102",  # Exception must not use an f-string literal
    "SIM117", # Use a single `with` statement with multiple contexts instead of nested `with` statements
    "G004",   # Logging statement uses f-string
    "S311",   # Standard pseudo-random generators are not suitable
    "LOG004", # `.exception()` call outside exception handlers
    "FBT",    # Boolean-typed positional argument in function definition
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed in `value`
    "ERA001", # Found commented-out code
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
known-first-party = ["streamlit_infrahub"]

[tool.ruff.lint.pycodestyle]
max-line-length = 150
